services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: finsight123
    ports:
      - "5432:5432"

  transaction-db:
    image: postgres:15
    container_name: transaction-db
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: finsight123
    ports:
      - "5434:5432"


